services:
    database:
        container_name: database
        image: postgres
        ports:
            - ${PG_PORT:-5432}:5432
        environment:
            POSTGRES_PASSWORD: ${PG_PASSWORD:-blogapp}
            POSTGRES_USER: ${PG_USER:-blogapp}
            POSTGRES_DB: ${PG_DATABASE:-blog}
        volumes:
            - database:/data/postgres
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -d postgres"]
            interval: 30s
            timeout: 10s
            retries: 5

    blog_backend:
        container_name: blog_backend
        working_dir: /app
        ports:
            - 8080:8080
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - ./:/app
        depends_on:
            - database

volumes:
    database:
