// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"database/sql"
)

type Post struct {
	ID            interface{}
	Title         string
	Content       string
	ParsedContent string
	Slug          string
	CreatedAt     sql.NullTime
	ModifiedAt    sql.NullTime
}
