// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	ID            int64
	Title         string
	Content       string
	ParsedContent string
	Slug          string
	CreatedAt     pgtype.Timestamp
	ModifiedAt    pgtype.Timestamp
}
