// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	ID            int64
	Title         string
	Content       string
	Toc           string
	ParsedContent string
	Slug          string
	CreatedAt     pgtype.Timestamp
	ModifiedAt    pgtype.Timestamp
	Description   pgtype.Text
	Readtime      pgtype.Int4
}

type Tag struct {
	ID         int64
	Name       string
	CreatedAt  pgtype.Timestamp
	ModifiedAt pgtype.Timestamp
}

type TagsPost struct {
	TagID      int64
	PostID     int64
	CreatedAt  pgtype.Timestamp
	ModifiedAt pgtype.Timestamp
}
