// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: posts.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPost = `-- name: CreatePost :one
insert into posts (title, toc, content, parsed_content, description, slug, created_at, modified_at)
values ($1, $2, $3, $4, $5, $6, $7, $8)
returning id, title, content, toc, parsed_content, slug, created_at, modified_at, description
`

type CreatePostParams struct {
	Title         string
	Toc           string
	Content       string
	ParsedContent string
	Description   pgtype.Text
	Slug          string
	CreatedAt     pgtype.Timestamp
	ModifiedAt    pgtype.Timestamp
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.Title,
		arg.Toc,
		arg.Content,
		arg.ParsedContent,
		arg.Description,
		arg.Slug,
		arg.CreatedAt,
		arg.ModifiedAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Toc,
		&i.ParsedContent,
		&i.Slug,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Description,
	)
	return i, err
}

const deletePostBySlug = `-- name: DeletePostBySlug :exec
delete from posts
where slug = $1
`

func (q *Queries) DeletePostBySlug(ctx context.Context, slug string) error {
	_, err := q.db.Exec(ctx, deletePostBySlug, slug)
	return err
}

const getPostBySlug = `-- name: GetPostBySlug :one
select id, title, content, toc, parsed_content, slug, created_at, modified_at, description
from posts
where slug = $1
`

func (q *Queries) GetPostBySlug(ctx context.Context, slug string) (Post, error) {
	row := q.db.QueryRow(ctx, getPostBySlug, slug)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Toc,
		&i.ParsedContent,
		&i.Slug,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Description,
	)
	return i, err
}

const getPosts = `-- name: GetPosts :many
select id, title, content, toc, parsed_content, slug, created_at, modified_at, description
from posts
order by created_at desc
`

func (q *Queries) GetPosts(ctx context.Context) ([]Post, error) {
	rows, err := q.db.Query(ctx, getPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Toc,
			&i.ParsedContent,
			&i.Slug,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostsByTag = `-- name: GetPostsByTag :many
select p.id, p.title, p.content, p.toc, p.parsed_content, p.slug, p.created_at, p.modified_at, p.description
from posts p
join tags_posts tp on p.id = tp.post_id
join tags t on t.id = tp.tag_id
where t.name = $1
order by p.created_at desc
`

func (q *Queries) GetPostsByTag(ctx context.Context, name string) ([]Post, error) {
	rows, err := q.db.Query(ctx, getPostsByTag, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Toc,
			&i.ParsedContent,
			&i.Slug,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePostBySlug = `-- name: UpdatePostBySlug :one
update posts
set title = $1, toc = $2, slug = $3, content = $4, parsed_content = $5, modified_at = $6, description = $7
where slug = $8
returning id, title, content, toc, parsed_content, slug, created_at, modified_at, description
`

type UpdatePostBySlugParams struct {
	Title         string
	Toc           string
	Slug          string
	Content       string
	ParsedContent string
	ModifiedAt    pgtype.Timestamp
	Description   pgtype.Text
	Slug_2        string
}

func (q *Queries) UpdatePostBySlug(ctx context.Context, arg UpdatePostBySlugParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePostBySlug,
		arg.Title,
		arg.Toc,
		arg.Slug,
		arg.Content,
		arg.ParsedContent,
		arg.ModifiedAt,
		arg.Description,
		arg.Slug_2,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Toc,
		&i.ParsedContent,
		&i.Slug,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Description,
	)
	return i, err
}
